matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
    - dist: trusty
      sudo: required


cache:
  directories:
    - node_modules
    - $HOME/.rvm
    - $HOME/.nvm
    - $HOME/.cabal
    - $HOME/.stack

sudo: false

language: node_js

node_js:
  - "4.2"
  - "5"
#   - "0.12"
#   - "0.10"
  - "iojs"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pandoc nvm libgit2 haskell-stack; fi
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; fi

install:
  - npm -g install npm@latest-2
  - npm install 
  - rvm install 2.2.1
  - bundle install
  - stack setup
  - stack install pandoc

before_script:
  - export PATH=$PATH:/home/travis/.cabal/bin

script:
  - bundle exec jekyll build --destination _site_jekyll
  - metalsmith build --destination _site_metalsmith

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
      - libstdc++-4.9-dev
      - haskell-platform
  code_climate:
      repo_token: b24eee69b925656c35879dd636cac1c382d5f07de0bd1c11b2197f9ec71c1d89

env:
  global:
    - GH_TOKEN=FAKE_TOKEN_FOR_TESTS
    - DEBUG=*